name: Code check

on:
  pull_request:
    branches-ignore:
      - "master"
    paths-ignore:
      - ".github/**"
      - "**.md"
  push:
    branches-ignore:
      - "dev"
    paths-ignore:
      - ".github/**"
      - "**.md"

jobs:
  test:
    name: Python tests and checks
    uses: ./.github/workflows/sub_testing.yml

  build:
    name: Build Python 🐍 distributions
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install requirements
        run: python -m pip install --user build
      - name: Cleaning
        run : python setup.py clean
      - name: Build Exegol
        run: python -m build --sdist --outdir dist/ .
